// ***************************************************************************
// *  Copyright 2012 Joseph Molnar
// *
// *  Licensed under the Apache License, Version 2.0 (the "License");
// *  you may not use this file except in compliance with the License.
// *  You may obtain a copy of the License at
// *
// *      http://www.apache.org/licenses/LICENSE-2.0
// *
// *  Unless required by applicable law or agreed to in writing, software
// *  distributed under the License is distributed on an "AS IS" BASIS,
// *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// *  See the License for the specific language governing permissions and
// *  limitations under the License.
// ***************************************************************************
package com.talvish.tales.contracts.services.http;

import javax.servlet.http.Cookie;

import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.talvish.tales.communication.Status;
import com.talvish.tales.contracts.data.DataContract;
import com.talvish.tales.system.Conditions;

/**
 * The result coming out of a resource method call.
 * @author jmolnar
 *
 * @param <V> the type of value generated by the resource method 
 */
@DataContract(name="lower")
public class ResourceResult<V> extends HttpResult<V,ResourceResult<V>> {
	/**
	 * Default, empty, constructor.
	 */
	public ResourceResult( ) {
	}
	
	/**
	 * Adds a header to return.
	 * If a header with the same name already exists 
	 * it will be replaced.
	 * @param theName the name of the header
	 * @param theValue the value to give the header
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> addHeader( String theName, String theValue ) {
		Conditions.checkParameter( !Strings.isNullOrEmpty( theName ), "need a name to add a header" );
		headers.put( theName, theValue );
		return this;
	}
	
	/**
	 * Adds a cookie to the return.
	 * If a cookie with the same name already exists
	 * it will be replaced.
	 * @param theCookie the cookie to be added
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> addCookie( Cookie theCookie ) {
		Conditions.checkParameter( theCookie != null, "need a cookie to add a cookie" );
		cookies.put( theCookie.getName(), theCookie );
		return this;
	}
	

	/**
	 * Sets the value and partial status information.
	 * @param theStatusCode the reason for the failure
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setResult( V theValue, Status theStatusCode ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		this.value = theValue;
		this.code = theStatusCode;
		this.subcode = null;
		this.subject = null;
		return this;
	}
	
	/**
	 * Sets the value and primary status information.
	 * @param theStatusCode the reason for the failure
	 * @param theStatusSubcode a code, handler specific, outlining the problem
	 * @param theSubject the subject of the status (e.g. parameter names when they are incorrect)
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setResult( V theValue, Status theStatusCode, String theStatusSubcode, String theSubject ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		this.value = theValue;
		this.code = theStatusCode;
		this.subcode = theStatusSubcode;
		this.subject = theSubject;
		return this;
	}
	
	/**
	 * Sets some status information but not the value.
	 * @param theStatusCode the reason for the failure
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setResult( Status theStatusCode ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		this.code = theStatusCode;
		this.subcode = null;
		this.subject = null;
		return this;
	}

	/**
	 * Sets the primary status information but not the value.
	 * @param theStatusCode the reason for the failure
	 * @param theStatusSubcode a code, handler specific, outlining the problem
	 * @param theSubject the subject of the status (e.g. parameter names when they are incorrect)
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setResult( Status theStatusCode, String theStatusSubcode, String theSubject ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		this.code = theStatusCode;
		this.subcode = theStatusSubcode;
		this.subject = theSubject;
		return this;
	}
	
	/**
	 * Sets the message to report. 
	 * This will perform a <code>String.format( theMessage, theParameters) </code>.
	 * @param theMessage the message to use
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setMessage( String theMessage ) {
		this.message = theMessage;
		return this;
	}
	
	/**
	 * Sets the message to report. 
	 * This will perform a <code>String.format( theMessage, theParameters) </code>.
	 * @param theMessage the message to use
	 * @param theParameters the parameters to use in the message
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setMessage( String theMessage, Object...theParameters ) {
		this.message = String.format( theMessage, theParameters );
		return this;
	}
	
	/**
	 * Sets the exception to report. 
	 * @param theException the exception to reprot
	 * @return returns itself so that calls can be chained together
	 */
	public ResourceResult<V> setException( Throwable theException ) {
		this.exception = theException;
		return this;
	}
}
