// ***************************************************************************
// *  Copyright 2012 Joseph Molnar
// *
// *  Licensed under the Apache License, Version 2.0 (the "License");
// *  you may not use this file except in compliance with the License.
// *  You may obtain a copy of the License at
// *
// *      http://www.apache.org/licenses/LICENSE-2.0
// *
// *  Unless required by applicable law or agreed to in writing, software
// *  distributed under the License is distributed on an "AS IS" BASIS,
// *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// *  See the License for the specific language governing permissions and
// *  limitations under the License.
// ***************************************************************************
package com.tales.contracts.services.http;

import com.google.common.base.Preconditions;
import com.tales.contracts.data.DataContract;
import com.tales.services.Status;

/**
 * The result coming out of a resource method call.
 * @author jmolnar
 *
 * @param <T> the type of value generated by the resource method 
 */
@DataContract(name="lower")
public class ResourceResult<T> extends HttpResult<T> {
	/**
	 * Default, empty, constructor.
	 */
	public ResourceResult( ) {
	}
	
	/**
	 * Adds a header to return.
	 * @param theName the name of the header
	 * @param theValue the value to give the header
	 */
	public void addHeader( String theName, String theValue ) {
		headers.put( theName, theValue );
	}
	
	/**
	 * Sets the value and HTTP status.
	 * @param theStatus the status value to use.
	 */
	public void setResult( T theValue, Status theStatusCode ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		Preconditions.checkArgument( !theStatusCode.isFailure( ), "the status code must not be a failure" );
		this.code = theStatusCode;
		this.value = theValue;
	}
	
	/**
	 * Sets the HTTP status, along with a lot of status information.
	 * @param theStatusCode the reason for the failure
	 * @param theStatusSubcode a code, handler specific, outlining the problem
	 * @param theFailureMessage the failure message to display
	 * @param theFailureException the exception, which may be null
	 */
	public void setResult( Status theStatusCode, String theStatusSubcode, String theFailureMessage, Throwable theFailureException ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		Preconditions.checkArgument(  theStatusCode.isFailure( ), "the status code must be a failure" );
		this.code = theStatusCode;
		this.subcode = theStatusSubcode;
		this.message = theFailureMessage;
		this.exception = theFailureException;
	}
	
	/**
	 * Sets the value, HTTP status, along with a lot of status information.
	 * @param theStatusCode the reason for the failure
	 * @param theStatusSubcode a code, handler specific, outlining the problem
	 * @param theFailureMessage the failure message to display
	 * @param theFailureException the exception, which may be null
	 */
	public void setResult( T theValue, Status theStatusCode, String theStatusSubcode, String theFailureMessage, Throwable theFailureException ) {
		Preconditions.checkNotNull( theStatusCode, "need a status code" );
		Preconditions.checkArgument(  theStatusCode.isFailure( ), "the status code must be a failure" );
		this.value = theValue;
		this.code = theStatusCode;
		this.subcode = theStatusSubcode;
		this.message = theFailureMessage;
		this.exception = theFailureException;
	}
}
